import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

export const apiSlice = createApi({
  reducerPath: "api",
  baseQuery: fetchBaseQuery({
    baseUrl: process.env.NEXT_PUBLIC_BACKEND_BASE_URL,
  }),
  tagTypes: [
    "home",
    "category",
    "products",
    "auth",
    "addToCart",
    "blogListing",
    "allBlogCategories",
    "addToWishlist",
    "getWishlist",
    "removeFromWishlist",
    "getCartData",
    "getBuyNowData",
    "getAvailableCoupons",
    "ProductsByCategory",
    "applyCoupon",
    "SearchProducts",
    "blog",
    "relatedBlogs",
    "reviews",
    "faqs",
    "product",
    "ProductsBySubCategory",
    "reviewApi",
    "updateReview",
    "deleteReview",
    "myProfile",
    "subscribeEmail",
    "getBannerData",
    "askQuestion",
    "getContactDetails",
    "orderHistory",
    "aboutUs",
    "getAllDeliveryAddresses",
    "shippingReturn",
    "orderInfo",
    "termUse",
    "getLocation",
    "returnPolicy",
    "privacyPolicy",
    "checkPincode",
    "buyingGuide",
    "trackOrder",
  ],
  overrideExisting: true,
  endpoints: (builder) => ({}),
});
